spring:
  profiles:
    active: mainPort
  mail:
    username: 1448602918@qq.com
    password: wvhfyvsogogzgcdg
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
---
spring:
  devtools:
    restart:
      enabled=true:
---
server:
  port: 8083
spring:
  profiles: mainPort
---
server:
  port: 8086
spring:
  profiles: backupPort
Login:
  username: admin
  password: admin






